library(shiny)
library(shinydashboard)
library(plotly)
library(shinythemes)
library(shinyjs)
library(DT)
library(tidyr)
library(ggplot2)
library(maps) 
library(stringr)
library(tidyverse)
library(reshape2)
library(ggrepel)
library(plyr)
library(tableHTML)
library(GGally)
library(scales)
library(plyr)
library(dplyr)
source('ui.R', local = TRUE)
source('server.R')
shinyApp(ui=ui,server = server)
